name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m unittest src/python/tests/tests.py

  lint-and-fix:
    name: Auto Lint and Fix
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort

      - name: Run Ruff with autofix
        run: ruff check . --fix
        continue-on-error: true

      - name: Run Black
        run: black .

      - name: Run isort
        run: isort .

      - name: Download google-java-format
        run: |
          mkdir -p /tmp/tools
          curl -L -o /tmp/tools/gjf.jar https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar

      - name: Format Java files
        run: |
          find . -name "*.java" > /tmp/java_files.txt
          xargs -a /tmp/java_files.txt java -jar /tmp/tools/gjf.jar --replace

      - name: Commit and push changes if needed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add . && git commit -m "style: auto-fix using ruff, black, isort" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
